#!wit/toml
author="CLAM"
description="Find unused subroutines and variables in Perl code"
enabled=true
license="Artistic-2.0"
name="perl_dead_code"
notes="Scans for sub definitions and variable declarations.\nChecks if each is referenced elsewhere in code.\n"
priority=10
timeout=10
type="rule"
usage="Input: { code: \"sub used { } sub unused { } my $x = 1;\" }\nOutput: { unused_subs: [\"unused\"], unused_vars: [\"$x\"] }\n"
version="1.0.0"
triggers=[
  "perl_dead_code",
]

[metadata]
category="perl"
complexity="simple"
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $code = ref $input eq 'HASH' ? ($input->{code} // '') : $input;

return { unused_subs => [], unused_vars => [] } unless $code;

# Find all sub definitions
my @subs;
while ($code =~ /^sub\s+(\w+)/gm) {
    push @subs, $1;
}

# Find all variable declarations
my @vars;
while ($code =~ /\bmy\s+(\$[\w]+)/g) {
    push @vars, $1;
}

# Check which subs are actually called
my @unused_subs;
for my $sub (@subs) {
    my $escaped = quotemeta($sub);
    my @refs = ($code =~ /\b$escaped\b/g);
    push @unused_subs, $sub if @refs <= 1;  # Only the definition
}

# Check which vars are actually used
my @unused_vars;
for my $var (@vars) {
    my $escaped = quotemeta($var);
    my @refs = ($code =~ /\b$escaped\b/g);
    push @unused_vars, $var if @refs <= 1;  # Only the declaration
}

return {
    unused_subs => \@unused_subs,
    unused_vars => \@unused_vars,
};

PERL
