#!wit/toml
author="CLAM"
description="Extract or generate POD documentation for Perl code"
enabled=true
license="Artistic-2.0"
name="perl_doc"
notes="extract: Pulls existing POD from code.\ngenerate: Creates POD from function signatures and comments.\n"
priority=10
timeout=10
type="rule"
usage="Input: { code: \"sub foo { ... }\", action: \"extract\" }\nInput: { code: \"sub foo { ... }\", action: \"generate\" }\nOutput: { pod: \"=head1 foo\\n\\nDescription\\n...\" }\n"
version="1.0.0"
triggers=[
  "perl_doc",
]

[metadata]
category="perl"
complexity="simple"
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $code = ref $input eq 'HASH' ? ($input->{code} // '') : $input;
my $action = ref $input eq 'HASH' ? ($input->{action} // 'extract') : 'extract';

return { pod => '', error => "No code provided" } unless $code;

if ($action eq 'extract') {
    my $pod = '';
    my $in_pod = 0;
    for my $line (split /\n/, $code) {
        if ($line =~ /^=(\w+)/) {
            $in_pod = 1;
            $pod .= "$line\n";
        } elsif ($line =~ /^=cut/) {
            $in_pod = 0;
            $pod .= "$line\n";
        } elsif ($in_pod) {
            $pod .= "$line\n";
        }
    }
    return { pod => $pod || "No POD found" };
}

if ($action eq 'generate') {
    my @subs;
    while ($code =~ /^sub\s+(\w+)\s*(?:\{|\(([^)]*)\)\s*\{)/gm) {
        my $name = $1;
        my $args = $2 // '';
        push @subs, { name => $name, args => $args };
    }

    my $pod = "=head1 NAME\n\nModule - Description\n\n";
    $pod .= "=head1 SYNOPSIS\n\n    use Module;\n\n";
    $pod .= "=head1 DESCRIPTION\n\n";
    $pod .= "This module provides functionality.\n\n";

    for my $sub (@subs) {
        $pod .= "=head2 $sub->{name}\n\n";
        $pod .= "    $sub->{name}($sub->{args})\n\n";
        $pod .= "Description of $sub->{name}.\n\n";
    }

    $pod .= "=head1 AUTHOR\n\nCLAM\n\n=cut\n";

    return { pod => $pod };
}

return { error => "Unknown action: $action" };

PERL
