#!wit/toml
author="CLAM"
description="Generate test skeletons from function signatures"
enabled=true
license="Artistic-2.0"
name="perl_test_gen"
notes="Parses function signatures.\nGenerates basic test cases with edge cases.\n"
priority=10
timeout=10
type="rule"
usage="Input: { code: \"sub add { my ($a, $b) = @_; return $a + $b; }\" }\nOutput: { test: \"use Test::More;\\nsubtest 'add' => sub {\\n    is(add(1,2), 3, 'basic');\\n};\" }\n"
version="1.0.0"
requires_perl=[
  "PPI",
]
triggers=[
  "perl_test_gen",
]

[metadata]
category="perl"
complexity="simple"
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $code = ref $input eq 'HASH' ? ($input->{code} // '') : $input;

return { test => '', error => "No code provided" } unless $code;

my @tests;

while ($code =~ /^sub\s+(\w+)\s*(?:\{|\(([^)]*)\)\s*\{)/gm) {
    my $name = $1;
    my $args = $2 // '';

    my $test = "use Test::More;\n\n";
    $test .= "subtest '$name' => sub {\n";
    $test .= "    # TODO: Add test cases\n";
    $test .= "    ok(1, '$name runs without error');\n";
    $test .= "};\n\n";
    $test .= "done_testing();\n";

    push @tests, { name => $name, test => $test };
}

if (@tests) {
    return {
        tests => [map { $_->{test} } @tests],
        names => [map { $_->{name} } @tests],
    };
}

return { test => '', error => "No subroutines found" };

PERL
