#!wit/toml
author="CLAM"
description="Add trace/debug output to Perl code"
enabled=true
license="Artistic-2.0"
name="perl_trace"
notes="Injects warn statements at entry/exit points.\nLevels: basic (entry/exit), args (with arguments), full (with return values).\n"
priority=10
timeout=10
type="rule"
usage="Input: { code: \"sub foo { return bar(); }\", level: \"basic\" }\nOutput: { traced: \"sub foo { warn 'TRACE: foo called'; my $result = bar(); warn 'TRACE: foo returned ' . $result; return $result; }\" }\n"
version="1.0.0"
requires_perl=[
  "Devel::Cover",
]
triggers=[
  "perl_trace",
]

[metadata]
category="perl"
complexity="simple"
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $code = ref $input eq 'HASH' ? ($input->{code} // '') : $input;
my $level = ref $input eq 'HASH' ? ($input->{level} // 'basic') : 'basic';

return { traced => $code, error => "No code provided" } unless $code;

my $traced = $code;

# Add trace to each sub
$traced =~ s/^sub\s+(\w+)\s*\{/sub $1 {\n    warn "TRACE: $1 called" if \$ENV{CLAM_TRACE};/gm;

if ($level eq 'args' || $level eq 'full') {
    $traced =~ s/warn "TRACE: (\w+) called"/warn "TRACE: $1 called with args: " . join(", ", \@_)/g;
}

if ($level eq 'full') {
    # Add return value tracing (basic heuristic)
    $traced =~ s/return\s+(.+?);/my \$result = $1; warn "TRACE: returning \$result"; return \$result;/g;
}

return { traced => $traced };

PERL
