#!wit/toml
author="CLAM"
description="Rule: classify fix"
enabled=1
name="classify_fix"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_fix",
]

[metadata]
author="CLAM"
description="Classify fix/bug/error inputs into debug domain"
version=1.0
triggers=[
  "classify_fix",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:fix|bug|error|crash|fail)/i) {
    return { domain => 'debug', mode => 'debug', confidence => 1.0 };
}
return undef;

PERL
