#!wit/toml
author="CLAM"
description="Rule: classify auth"
enabled=1
name="classify_auth"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_auth",
]

[metadata]
author="CLAM"
description="Classify auth-related input"
priority=10
version=1.0
triggers=[
  "classify_auth",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /\b(?:jwt|token|login|password|session|auth|oauth)\b/i) {
    return { domain => 'auth', tags => [qw(auth security)] };
}
return undef;

PERL
