#!wit/toml
author="CLAM"
description="Rule: classify build"
enabled=1
name="classify_build"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_build",
]

[metadata]
author="CLAM"
description="Classify build-related input"
priority=10
version=1.0
triggers=[
  "classify_build",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /\b(?:makefile|compile|build|install|package|cpan|module)\b/i) {
    return { domain => 'build', tags => [qw(build tooling)] };
}
return undef;

PERL
