#!wit/toml
author="CLAM"
description="Rule: classify test"
enabled=1
name="classify_test"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_test",
]

[metadata]
author="CLAM"
description="Classify test-related input"
priority=10
version=1.0
triggers=[
  "classify_test",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /\b(?:test|assert|expect|spec|describe|it\(|ok\(|is\(|use_ok)\b/i) {
    return { domain => 'test', tags => [qw(testing quality)] };
}
return undef;

PERL
