#!wit/toml
author="CLAM"
description="Rule: classify perl"
enabled=1
name="classify_perl"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_perl",
]

[metadata]
author="CLAM"
description="Classify Perl code input"
priority=10
version=1.0
triggers=[
  "classify_perl",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /\b(?:sub |use |package |my \$|our \$|=head|=cut|=>|->)\b/) {
    return { domain => 'perl', tags => [qw(perl code)] };
}
return undef;

PERL
