#!wit/toml
author="CLAM"
description="Rule: classify api"
enabled=1
name="classify_api"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_api",
]

[metadata]
author="CLAM"
description="Classify API-related input"
priority=10
version=1.0
triggers=[
  "classify_api",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /\b(?:route|endpoint|request|response|http|rest|api|url)\b/i) {
    return { domain => 'api', tags => [qw(http web)] };
}
return undef;

PERL
