#!wit/toml
author="CLAM"
description="Rule: classify query"
enabled=1
name="classify_query"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "classify_query",
]

[metadata]
author="CLAM"
description="Classify query/explanation inputs into query domain"
version=1.0
triggers=[
  "classify_query",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:what|how|why|where|when|who|explain|describe|show)/i) {
    return { domain => 'query', mode => 'plan', confidence => 1.0 };
}
return undef;

PERL
