#!wit/toml
author="CLAM"
description="Rule: detect no warnings"
enabled=1
name="detect_no_warnings"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "detect_no_warnings",
]

[metadata]
author="CLAM"
description="Detect missing 'use warnings'"
priority=5
version=1.0
triggers=[
  "detect_no_warnings",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if (($text =~ /\.pm$/ || $text =~ /\.pl$/) && $text !~ /^use warnings;/m) {
    return { found => 0, suggestion => 'Add "use warnings;" at top' };
}
return undef;

PERL
