#!wit/toml
author="CLAM"
description="Rule: intent refactor"
enabled=1
name="intent_refactor"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "intent_refactor",
]

[metadata]
author="CLAM"
description="Detect refactor intent"
priority=20
version=1.0
triggers=[
  "intent_refactor",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:refactor|clean|simplify|extract|move)\b/i) {
    return { intent => 'refactor', mode => 'build' };
}
return undef;

PERL
