#!wit/toml
author="CLAM"
description="Rule: intent explain"
enabled=1
name="intent_explain"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "intent_explain",
]

[metadata]
author="CLAM"
description="Detect explain intent"
priority=20
version=1.0
triggers=[
  "intent_explain",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:what|how|why|explain|describe|show)\b/i) {
    return { intent => 'explain', mode => 'plan' };
}
return undef;

PERL
