#!wit/toml
author="CLAM"
description="Rule: intent fix"
enabled=1
name="intent_fix"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "intent_fix",
]

[metadata]
author="CLAM"
description="Detect fix/bug intent"
priority=20
version=1.0
triggers=[
  "intent_fix",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:fix|bug|error|broken|issue|problem)\b/i) {
    return { intent => 'fix', mode => 'debug' };
}
return undef;

PERL
