#!wit/toml
author="CLAM"
description="Rule: intent build"
enabled=1
name="intent_build"
priority=10
stateful=0
timeout=5
type="rule"
version="1.0.0"
triggers=[
  "intent_build",
]

[metadata]
author="CLAM"
description="Detect build intent"
priority=20
version=1.0
triggers=[
  "intent_build",
]
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $text = ref $input eq 'HASH' ? ($input->{text} // '') : $input;
if ($text =~ /^(?:make|create|build|add|implement|write)\b/i) {
    return { intent => 'build', mode => 'build' };
}
return undef;

PERL
