#!wit/toml
author="CLAM"
description="Get file metadata (size, permissions, timestamps)"
enabled=true
license="Artistic-2.0"
name="fs_info"
notes="Read-only. Returns file metadata.\n"
priority=10
timeout=5
type="rule"
usage="Input: { path: \"/home/user/file.txt\" }\nOutput: { size: 1234, permissions: \"0644\", modified: \"...\", created: \"...\" }\n"
version="1.0.0"
triggers=[
  "fs_info",
]

[metadata]
category="filesystem"
complexity="simple"
safety="read_only"
source = <<'PERL'
my ($self, $input, %ctx) = @_;
my $path = ref $input eq 'HASH' ? ($input->{path} // '') : $input;

return { error => "No path provided" } unless $path;
return { error => "File not found: $path" } unless -e $path;

my @stat = stat($path);
return { error => "Cannot stat: $!" } unless @stat;

my $perm = sprintf("%04o", $stat[2] & 07777);

return {
    path       => $path,
    size       => $stat[7],
    permissions => $perm,
    uid        => $stat[4],
    gid        => $stat[5],
    modified   => scalar localtime($stat[9]),
    accessed   => scalar localtime($stat[8]),
    changed    => scalar localtime($stat[10]),
    is_file    => -f $path,
    is_dir     => -d $path,
    is_link    => -l $path,
};

PERL
